import { ModeToggle } from "@/components/ModeToggle";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Separator } from "@/components/ui/separator";
import { Toaster } from "@/components/ui/toaster";
import { Keyboard } from "lucide-react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";
import PhoneComponent from "./PhoneComponent";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "2i1k",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main>
            <div className="grid grid-rows-[3_1fr]">
            <div>
              <div className="flex items-center justify-between p-4 w-screen">
                <Link href="/" className="flex items-center justify-center">
                  <div className="bg-gray-100 rounded-md">
                    <Keyboard color="black" className="m-2" />
                  </div>
                  <h1 className="text-xl font-bold pl-4">
                    2 idiots, 1 keyboard
                  </h1>
                </Link>
                <div className="flex items-center justify-center">
                  <ModeToggle />
                </div>
              </div>
              <Separator />
            </div>
            <div className="hidden sm:block">{children}</div>
            <div className="block sm:hidden"><PhoneComponent /></div>
            </div>
          </main>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
